auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /marshall/:title

title: Marshall space
url: https://marshallma.github.io/marshall
feed: /atom.xml
author_info: <a href="https://marshallma.github.io/marshall/">Marshall</a>
